server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  config:
    import: configserver:http://localhost:8085 #import config from server
#  profiles:
#    active: dev #import config from application-dev.yml present on github through config server
#      sometimes dialect related error can come when hibernate can not be detected.
#      Use ctrl+n -> search mysqlDialect
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#
#
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka



