server:
  port: 8084
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      mvc:
        routes:
          - id: USER-SERVICE
            uri: lb://USER-SERVICE
            predicates:
              - Path=/users/**

          - id: HOTEL-SERVICE
            uri: lb://HOTEL-SERVICE
            predicates:
              - Path=/hotels/**

          - id: RATING-SERVICE
            uri: lb://RATING-SERVICE
            predicates:
              - Path=/ratings/**
  config:
    import: optional:configserver:http://localhost:8085 #ip address of config server


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true       #fetch registry details of service registry so that it will register with server
#    register-with-eureka: true #register will eureka service registry
#
#
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka # So that it will land on this ip address of eureka
